In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_rows',300)

# CO2 Data

In [3]:
#import emission csv
emission_csv = "../Resources/CO2_Emission-gaseous,liquid,solid,all.csv"
emission = pd.read_csv(emission_csv)

In [4]:
emission = emission.dropna(how='any')
emission = emission.drop(['Series Code','2021 [YR2021]','2020 [YR2020]','Country Name'],axis=1)
emission = emission.replace('..','0')

In [5]:
print(emission['Series Name'].unique())

['Population, total' 'CO2 emissions from solid fuel consumption (kt)'
 'CO2 emissions from liquid fuel consumption (kt)'
 'CO2 emissions from gaseous fuel consumption (kt)' 'CO2 emissions (kt)'
 'CO2 emissions from gaseous fuel consumption (% of total)'
 'CO2 emissions from liquid fuel consumption (% of total)'
 'CO2 emissions from solid fuel consumption (% of total)']

In [6]:
total_emission = emission.loc[emission['Series Name'] == 'CO2 emissions (kt)']

In [7]:
gas_emission_percentage = emission.loc[emission['Series Name'] == 'CO2 emissions from gaseous fuel consumption (% of total)']

In [8]:
liquid_emission_percentage = emission.loc[emission['Series Name'] == 'CO2 emissions from liquid fuel consumption (% of total)']

In [9]:
solid_emission_percentage = emission.loc[emission['Series Name'] == 'CO2 emissions from solid fuel consumption (% of total)']

In [10]:
# population = population.rename(columns={'Country Name':'Country'})

# Country Data

In [11]:
#import countries csv
country_csv = "../Resources/LatLong.csv"
country = pd.read_csv(country_csv)

In [12]:
country = country.dropna(how='any')

In [13]:
country.dtypes

Country          object
Country Code     object
Lat             float64
Long            float64
dtype: object

# Country Codes

In [14]:
#import countries code csv
code_csv = "../Resources/CountryCodes.csv"
code = pd.read_csv(code_csv)

In [15]:
code.columns

Index(['FIFA', 'Dial', 'ISO3166-1-Alpha-3', 'MARC', 'is_independent',
       'ISO3166-1-numeric', 'GAUL', 'FIPS', 'WMO', 'ISO3166-1-Alpha-2', 'ITU',
       'IOC', 'DS', 'UNTERM Spanish Formal', 'Global Code',
       'Intermediate Region Code', 'official_name_fr', 'UNTERM French Short',
       'ISO4217-currency_name', 'Developed / Developing Countries',
       'UNTERM Russian Formal', 'UNTERM English Short',
       'ISO4217-currency_alphabetic_code',
       'Small Island Developing States (SIDS)', 'UNTERM Spanish Short',
       'ISO4217-currency_numeric_code', 'UNTERM Chinese Formal',
       'UNTERM French Formal', 'UNTERM Russian Short', 'M49',
       'Sub-region Code', 'Region Code', 'official_name_ar',
       'ISO4217-currency_minor_unit', 'UNTERM Arabic Formal',
       'UNTERM Chinese Short', 'Land Locked Developing Countries (LLDC)',
       'Intermediate Region Name', 'official_name_es', 'UNTERM English Formal',
       'official_name_cn', 'official_name_en', 'ISO4217-currency_country_name',
       'Least Developed Countries (LDC)', 'Region Name', 'UNTERM Arabic Short',
       'Sub-region Name', 'official_name_ru', 'Global Name', 'Capital',
       'Continent', 'TLD', 'Languages', 'Geoname ID', 'CLDR display name',
       'EDGAR'],
      dtype='object')

In [16]:
code = code[['CLDR display name', 'ISO3166-1-Alpha-2', 'ISO3166-1-Alpha-3']]

# Match Country Codes

In [17]:
country_three = country.merge(code, how='left', left_on='Country Code', right_on='ISO3166-1-Alpha-2', sort=True)

In [18]:
country_three = country_three.drop(['CLDR display name','Country Code'],axis=1)

In [19]:
country_three = country_three.rename(columns={'ISO3166-1-Alpha-3':'Country Code'})
country_three

,Country,Lat,Long,ISO3166-1-Alpha-2,Country Code
0,Andorra,42.546245,1.601554,AD,AND
1,United Arab Emirates,23.424076,53.847818,AE,ARE
2,Afghanistan,33.939110,67.709953,AF,AFG
3,Antigua and Barbuda,17.060816,-61.796428,AG,ATG
4,Anguilla,18.220554,-63.068615,AI,AIA
5,Albania,41.153332,20.168331,AL,ALB
6,Armenia,40.069099,45.038189,AM,ARM
7,Netherlands Antilles,12.226079,-69.060087,NaN,NaN
8,Angola,-11.202692,17.873887,AO,AGO
9,Antarctica,-75.250973,-0.071389,AQ,ATA
10,Argentina,-38.416097,-63.616672,AR,ARG
11,American Samoa,-14.270972,-170.132217,AS,ASM
12,Austria,47.516231,14.550072,AT,AUT
13,Australia,-25.274398,133.775136,AU,AUS
14,Aruba,12.521110,-69.968338,AW,ABW
15,Azerbaijan,40.143105,47.576927,AZ,AZE
16,Bosnia and Herzegovina,43.915886,17.679076,BA,BIH
17,Barbados,13.193887,-59.543198,BB,BRB
18,Bangladesh,23.684994,90.356331,BD,BGD
19,Belgium,50.503887,4.469936,BE,BEL
20,Burkina Faso,12.238333,-1.561593,BF,BFA
21,Bulgaria,42.733883,25.485830,BG,BGR
22,Bahrain,25.930414,50.637772,BH,BHR
23,Burundi,-3.373056,29.918886,BI,BDI
24,Benin,9.307690,2.315834,BJ,BEN
25,Bermuda,32.321384,-64.757370,BM,BMU
26,Brunei,4.535277,114.727669,BN,BRN
27,Bolivia,-16.290154,-63.588653,BO,BOL
28,Brazil,-14.235004,-51.925280,BR,BRA
29,Bahamas,25.034280,-77.396280,BS,BHS
30,Bhutan,27.514162,90.433601,BT,BTN
31,Bouvet Island,-54.423199,3.413194,BV,BVT
32,Botswana,-22.328474,24.684866,BW,BWA
33,Belarus,53.709807,27.953389,BY,BLR
34,Belize,17.189877,-88.497650,BZ,BLZ
35,Canada,56.130366,-106.346771,CA,CAN
36,Cocos [Keeling] Islands,-12.164165,96.870956,CC,CCK
37,Congo [DRC],-4.038333,21.758664,CD,COD
38,Central African Republic,6.611111,20.939444,CF,CAF
39,Congo [Republic],-0.228021,15.827659,CG,COG
40,Switzerland,46.818188,8.227512,CH,CHE
41,Côte d'Ivoire,7.539989,-5.547080,CI,CIV
42,Cook Islands,-21.236736,-159.777671,CK,COK
43,Chile,-35.675147,-71.542969,CL,CHL
44,Cameroon,7.369722,12.354722,CM,CMR
45,China,35.861660,104.195397,CN,CHN
46,Colombia,4.570868,-74.297333,CO,COL
47,Costa Rica,9.748917,-83.753428,CR,CRI
48,Cuba,21.521757,-77.781167,CU,CUB
49,Cape Verde,16.002082,-24.013197,CV,CPV
50,Christmas Island,-10.447525,105.690449,CX,CXR
51,Cyprus,35.126413,33.429859,CY,CYP
52,Czech Republic,49.817492,15.472962,CZ,CZE
53,Germany,51.165691,10.451526,DE,DEU
54,Djibouti,11.825138,42.590275,DJ,DJI
55,Denmark,56.263920,9.501785,DK,DNK
56,Dominica,15.414999,-61.370976,DM,DMA
57,Dominican Republic,18.735693,-70.162651,DO,DOM
58,Algeria,28.033886,1.659626,DZ,DZA
59,Ecuador,-1.831239,-78.183406,EC,ECU
60,Estonia,58.595272,25.013607,EE,EST
61,Egypt,26.820553,30.802498,EG,EGY
62,Western Sahara,24.215527,-12.885834,EH,ESH
63,Eritrea,15.179384,39.782334,ER,ERI
64,Spain,40.463667,-3.749220,ES,ESP
65,Ethiopia,9.145000,40.489673,ET,ETH
66,Finland,61.924110,25.748151,FI,FIN
67,Fiji,-16.578193,179.414413,FJ,FJI
68,Falkland Islands [Islas Malvinas],-51.796253,-59.523613,FK,FLK
69,Micronesia,7.425554,150.550812,FM,FSM
70,Faroe Islands,61.892635,-6.911806,FO,FRO
71,France,46.227638,2.213749,FR,FRA
72,Gabon,-0.803689,11.609444,GA,GAB
73,United Kingdom,55.378051,-3.435973,GB,GBR
74,Grenada,12.262776,-61.604171,GD,GRD
75,Georgia,42.315407,43.356892,GE,GEO
76,French Guiana,3.933889,-53.125782,GF,GUF
77,Guernsey,49.465691,-2.585278,GG,GGY
78,Ghana,7.946527,-1.023194,GH,GHA
79,Gibraltar,36.137741,-5.345374,GI,GIB
80,Greenland,71.706936,-42.604303,GL,GRL
81,Gambia,13.443182,-15.310139,GM,GMB
82,Guinea,9.945587,-9.696645,GN,GIN
83,Guadeloupe,16.995971,-62.067641,GP,GLP
84,Equatorial Guinea,1.650801,10.267895,GQ,GNQ
85,Greece,39.074208,21.824312,GR,GRC
86,South Georgia and the South Sandwich Islands,-54.429579,-36.587909,GS,SGS
87,Guatemala,15.783471,-90.230759,GT,GTM
88,Guam,13.444304,144.793731,GU,GUM
89,Guinea-Bissau,11.803749,-15.180413,GW,GNB
90,Guyana,4.860416,-58.930180,GY,GUY
91,Gaza Strip,31.354676,34.308825,NaN,NaN
92,Hong Kong,22.396428,114.109497,HK,HKG
93,Heard Island and McDonald Islands,-53.081810,73.504158,HM,HMD
94,Honduras,15.199999,-86.241905,HN,HND
95,Croatia,45.100000,15.200000,HR,HRV
96,Haiti,18.971187,-72.285215,HT,HTI
97,Hungary,47.162494,19.503304,HU,HUN
98,Indonesia,-0.789275,113.921327,ID,IDN
99,Ireland,53.412910,-8.243890,IE,IRL
100,Israel,31.046051,34.851612,IL,ISR
101,Isle of Man,54.236107,-4.548056,IM,IMN
102,India,20.593684,78.962880,IN,IND
103,British Indian Ocean Territory,-6.343194,71.876519,IO,IOT
104,Iraq,33.223191,43.679291,IQ,IRQ
105,Iran,32.427908,53.688046,IR,IRN
106,Iceland,64.963051,-19.020835,IS,ISL
107,Italy,41.871940,12.567380,IT,ITA
108,Jersey,49.214439,-2.131250,JE,JEY
109,Jamaica,18.109581,-77.297508,JM,JAM
110,Jordan,30.585164,36.238414,JO,JOR
111,Japan,36.204824,138.252924,JP,JPN
112,Kenya,-0.023559,37.906193,KE,KEN
113,Kyrgyzstan,41.204380,74.766098,KG,KGZ
114,Cambodia,12.565679,104.990963,KH,KHM
115,Kiribati,-3.370417,-168.734039,KI,KIR
116,Comoros,-11.875001,43.872219,KM,COM
117,Saint Kitts and Nevis,17.357822,-62.782998,KN,KNA
118,North Korea,40.339852,127.510093,KP,PRK
119,South Korea,35.907757,127.766922,KR,KOR
120,Kuwait,29.311660,47.481766,KW,KWT
121,Cayman Islands,19.513469,-80.566956,KY,CYM
122,Kazakhstan,48.019573,66.923684,KZ,KAZ
123,Laos,19.856270,102.495496,LA,LAO
124,Lebanon,33.854721,35.862285,LB,LBN
125,Saint Lucia,13.909444,-60.978893,LC,LCA
126,Liechtenstein,47.166000,9.555373,LI,LIE
127,Sri Lanka,7.873054,80.771797,LK,LKA
128,Liberia,6.428055,-9.429499,LR,LBR
129,Lesotho,-29.609988,28.233608,LS,LSO
130,Lithuania,55.169438,23.881275,LT,LTU
131,Luxembourg,49.815273,6.129583,LU,LUX
132,Latvia,56.879635,24.603189,LV,LVA
133,Libya,26.335100,17.228331,LY,LBY
134,Morocco,31.791702,-7.092620,MA,MAR
135,Monaco,43.750298,7.412841,MC,MCO
136,Moldova,47.411631,28.369885,MD,MDA
137,Montenegro,42.708678,19.374390,ME,MNE
138,Madagascar,-18.766947,46.869107,MG,MDG
139,Marshall Islands,7.131474,171.184478,MH,MHL
140,Macedonia [FYROM],41.608635,21.745275,MK,MKD
141,Mali,17.570692,-3.996166,ML,MLI
142,Myanmar [Burma],21.913965,95.956223,MM,MMR
143,Mongolia,46.862496,103.846656,MN,MNG
144,Macau,22.198745,113.543873,MO,MAC
145,Northern Mariana Islands,17.330830,145.384690,MP,MNP
146,Martinique,14.641528,-61.024174,MQ,MTQ
147,Mauritania,21.007890,-10.940835,MR,MRT
148,Montserrat,16.742498,-62.187366,MS,MSR
149,Malta,35.937496,14.375416,MT,MLT
150,Mauritius,-20.348404,57.552152,MU,MUS
151,Maldives,3.202778,73.220680,MV,MDV
152,Malawi,-13.254308,34.301525,MW,MWI
153,Mexico,23.634501,-102.552784,MX,MEX
154,Malaysia,4.210484,101.975766,MY,MYS
155,Mozambique,-18.665695,35.529562,MZ,MOZ
156,New Caledonia,-20.904305,165.618042,NC,NCL
157,Niger,17.607789,8.081666,NE,NER
158,Norfolk Island,-29.040835,167.954712,NF,NFK
159,Nigeria,9.081999,8.675277,NG,NGA
160,Nicaragua,12.865416,-85.207229,NI,NIC
161,Netherlands,52.132633,5.291266,NL,NLD
162,Norway,60.472024,8.468946,NO,NOR
163,Nepal,28.394857,84.124008,NP,NPL
164,Nauru,-0.522778,166.931503,NR,NRU
165,Niue,-19.054445,-169.867233,NU,NIU
166,New Zealand,-40.900557,174.885971,NZ,NZL
167,Oman,21.512583,55.923255,OM,OMN
168,Panama,8.537981,-80.782127,PA,PAN
169,Peru,-9.189967,-75.015152,PE,PER
170,French Polynesia,-17.679742,-149.406843,PF,PYF
171,Papua New Guinea,-6.314993,143.955550,PG,PNG
172,Philippines,12.879721,121.774017,PH,PHL
173,Pakistan,30.375321,69.345116,PK,PAK
174,Poland,51.919438,19.145136,PL,POL
175,Saint Pierre and Miquelon,46.941936,-56.271110,PM,SPM
176,Pitcairn Islands,-24.703615,-127.439308,PN,PCN
177,Puerto Rico,18.220833,-66.590149,PR,PRI
178,Palestinian Territories,31.952162,35.233154,PS,PSE
179,Portugal,39.399872,-8.224454,PT,PRT
180,Palau,7.514980,134.582520,PW,PLW
181,Paraguay,-23.442503,-58.443832,PY,PRY
182,Qatar,25.354826,51.183884,QA,QAT
183,Réunion,-21.115141,55.536384,RE,REU
184,Romania,45.943161,24.966760,RO,ROU
185,Serbia,44.016521,21.005859,RS,SRB
186,Russia,61.524010,105.318756,RU,RUS
187,Rwanda,-1.940278,29.873888,RW,RWA
188,Saudi Arabia,23.885942,45.079162,SA,SAU
189,Solomon Islands,-9.645710,160.156194,SB,SLB
190,Seychelles,-4.679574,55.491977,SC,SYC
191,Sudan,12.862807,30.217636,SD,SDN
192,Sweden,60.128161,18.643501,SE,SWE
193,Singapore,1.352083,103.819836,SG,SGP
194,Saint Helena,-24.143474,-10.030696,SH,SHN
195,Slovenia,46.151241,14.995463,SI,SVN
196,Svalbard and Jan Mayen,77.553604,23.670272,SJ,SJM
197,Slovakia,48.669026,19.699024,SK,SVK
198,Sierra Leone,8.460555,-11.779889,SL,SLE
199,San Marino,43.942360,12.457777,SM,SMR
200,Senegal,14.497401,-14.452362,SN,SEN
201,Somalia,5.152149,46.199616,SO,SOM
202,Suriname,3.919305,-56.027783,SR,SUR
203,São Tomé and Príncipe,0.186360,6.613081,ST,STP
204,El Salvador,13.794185,-88.896530,SV,SLV
205,Syria,34.802075,38.996815,SY,SYR
206,Swaziland,-26.522503,31.465866,SZ,SWZ
207,Turks and Caicos Islands,21.694025,-71.797928,TC,TCA
208,Chad,15.454166,18.732207,TD,TCD
209,French Southern Territories,-49.280366,69.348557,TF,ATF
210,Togo,8.619543,0.824782,TG,TGO
211,Thailand,15.870032,100.992541,TH,THA
212,Tajikistan,38.861034,71.276093,TJ,TJK
213,Tokelau,-8.967363,-171.855881,TK,TKL
214,Timor-Leste,-8.874217,125.727539,TL,TLS
215,Turkmenistan,38.969719,59.556278,TM,TKM
216,Tunisia,33.886917,9.537499,TN,TUN
217,Tonga,-21.178986,-175.198242,TO,TON
218,Turkey,38.963745,35.243322,TR,TUR
219,Trinidad and Tobago,10.691803,-61.222503,TT,TTO
220,Tuvalu,-7.109535,177.649330,TV,TUV
221,Taiwan,23.697810,120.960515,TW,TWN
222,Tanzania,-6.369028,34.888822,TZ,TZA
223,Ukraine,48.379433,31.165580,UA,UKR
224,Uganda,1.373333,32.290275,UG,UGA
225,United States,37.090240,-95.712891,US,USA
226,Uruguay,-32.522779,-55.765835,UY,URY
227,Uzbekistan,41.377491,64.585262,UZ,UZB
228,Vatican City,41.902916,12.453389,VA,VAT
229,Saint Vincent and the Grenadines,12.984305,-61.287228,VC,VCT
230,Venezuela,6.423750,-66.589730,VE,VEN
231,British Virgin Islands,18.420695,-64.639968,VG,VGB
232,U.S. Virgin Islands,18.335765,-64.896335,VI,VIR
233,Vietnam,14.058324,108.277199,VN,VNM
234,Vanuatu,-15.376706,166.959158,VU,VUT
235,Wallis and Futuna,-13.768752,-177.156097,WF,WLF
236,Samoa,-13.759029,-172.104629,WS,WSM
237,Kosovo,42.602636,20.902977,NaN,NaN
238,Yemen,15.552727,48.516388,YE,YEM
239,Mayotte,-12.827500,45.166244,YT,MYT
240,South Africa,-30.559482,22.937506,ZA,ZAF
241,Zambia,-13.133897,27.849332,ZM,ZMB
242,Zimbabwe,-19.015438,29.154857,ZW,ZWE

# Merging Dataframes

## Merging for each emission df

In [20]:
joined_total = country_three.merge(total_emission, how='left', left_on='Country Code', right_on='Country Code', sort=True)

In [21]:
joined_gas = country_three.merge(gas_emission_percentage, how='left', left_on='Country Code', right_on='Country Code', sort=True)

In [22]:
joined_liquid = country_three.merge(liquid_emission_percentage, how='left', left_on='Country Code', right_on='Country Code', sort=True)

In [23]:
joined_solid = country_three.merge(solid_emission_percentage, how='left', left_on='Country Code', right_on='Country Code', sort=True)

# Drop nulls

In [24]:
joined_total = joined_total.dropna(how='any')
joined_gas = joined_gas.dropna(how='any')
joined_liquid = joined_liquid.dropna(how='any')
joined_solid = joined_solid.dropna(how='any')

## Rename Columns

In [25]:
for x in range(1960,2020):
    joined_total = joined_total.rename(columns={f'{x} [YR{x}]':f'{x}'})
    joined_gas = joined_gas.rename(columns={f'{x} [YR{x}]':f'{x}'})
    joined_liquid = joined_liquid.rename(columns={f'{x} [YR{x}]':f'{x}'})
    joined_solid = joined_solid.rename(columns={f'{x} [YR{x}]':f'{x}'})

## Filter Years

In [26]:
for x in range(1960,1990):
    joined_total = joined_total.drop(f'{x}', axis=1)
    joined_gas = joined_gas.drop(f'{x}', axis=1)
    joined_liquid = joined_liquid.drop(f'{x}', axis=1)
    joined_solid = joined_solid.drop(f'{x}', axis=1)

## Change to 2 Character ID's

In [27]:
joined_total = joined_total.drop(['Country Code','Series Name'],axis=1)
joined_gas = joined_gas.drop(['Country Code','Series Name'],axis=1)
joined_liquid = joined_liquid.drop(['Country Code','Series Name'],axis=1)
joined_solid = joined_solid.drop(['Country Code','Series Name'],axis=1)

joined_total = joined_total.rename(columns={'ISO3166-1-Alpha-2':'Country Code'})
joined_gas = joined_gas.rename(columns={'ISO3166-1-Alpha-2':'Country Code'})
joined_liquid = joined_liquid.rename(columns={'ISO3166-1-Alpha-2':'Country Code'})
joined_solid = joined_solid.rename(columns={'ISO3166-1-Alpha-2':'Country Code'})

In [28]:
joined_total.head()

,Country,Lat,Long,Country Code,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,12.521110,-69.968338,AW,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,33.939110,67.709953,AF,2380,2230,1390,1340,1290,1240,...,7110.0001335144,8930.00030517578,8079.99992370605,5989.99977111816,4880.00011444092,5949.99980926514,5300.00019073486,4780.00020980835,6070.00017166138,6079.99992370605
2,Angola,-11.202692,17.873887,AO,6560,6670,6880,9270,11300,12720,...,22799.9992370605,23870.0008392334,23870.0008392334,26959.9990844727,29629.9991607666,31649.9996185303,29760.0002288818,24250,23959.9990844727,25209.9990844727
4,Albania,41.153332,20.168331,AL,5980,4060,2220,2060,2070,1930,...,4449.99980926514,4849.99990463257,4360.0001335144,4440.00005722046,4820.00017166138,4619.99988555908,4480.00001907349,5139.9998664856,5110.0001335144,4829.99992370605
5,Andorra,42.546245,1.601554,AD,410,410,410,410,410,430,...,519.999980926514,490.000009536743,490.000009536743,479.999989271164,460.00000834465,469.999998807907,469.999998807907,469.999998807907,490.000009536743,500

In [29]:
joined_gas.head()

,Country,Lat,Long,Country Code,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,12.521110,-69.968338,AW,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,33.939110,67.709953,AF,13.6273648648649,14.186204379562,25.3869230769231,25.8847058823529,25.9510769230769,25.81568,...,3.12985005767013,2.51246329526917,2.94763636363636,3.49032902467685,3.47449423815621,3.53390488110138,4.31703653585927,0,0,0
2,Angola,-11.202692,17.873887,AO,15.9888151658768,16.6222358346095,16.7519152276295,15.1994492753623,14.525485799701,9.72877551020408,...,4.80707325622152,4.76734894772573,4.70345785123967,2.33517062766606,1.67307536817788,4.09877986348123,4.22517932787348,0,0,0
4,Albania,41.153332,20.168331,AL,7.6976694214876,6.69160583941606,8.84008928571428,7.61743961352657,4.62658878504673,2.63271794871795,...,0.560458515283843,0.582063492063492,0.640524017467249,0.688997912317328,1.1239846743295,1.22956607495069,3.27277890466531,0,0,0
5,Andorra,42.546245,1.601554,AD,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
joined_liquid.head()

,Country,Lat,Long,Country Code,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,12.521110,-69.968338,AW,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,33.939110,67.709953,AF,62.5619932432432,62.7672627737226,64.8776923076923,65.7902941176471,66.006,66.006,...,67.7147289504037,62.0638254486134,64.7076363636364,56.2330787309048,48.3142509603073,59.3420650813517,47.0408119079838,0,0,0
2,Angola,-11.202692,17.873887,AO,39.1610110584518,34.9853139356815,35.9791993720565,43.0473913043478,19.4038565022421,78.1363543599258,...,46.9010970907816,48.731517311609,57.1324661157025,53.1837903717245,81.6206641640196,48.580449374289,50.640016944366,0,0,0
4,Albania,41.153332,20.168331,AL,35.9426611570248,54.2466180048662,63.1902678571429,71.568502415459,75.0535514018692,91.0168205128205,...,76.302423580786,74.9406746031746,68.9363973799127,69.5887891440501,73.9722413793103,65.8902761341223,68.2076876267749,0,0,0
5,Andorra,42.546245,1.601554,AD,99.2773170731707,99.2773170731707,99.2773170731707,100.171707317073,99.2773170731707,98.9237209302326,...,99.4321153846154,100.281224489796,99.5328571428571,99.3145833333333,100.443913043478,99.0870212765957,99.8672340425532,0,0,0

In [31]:
joined_solid.head()

,Country,Lat,Long,Country Code,1990,1991,1992,1993,1994,1995,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,12.521110,-69.968338,AW,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,33.939110,67.709953,AF,9.41527027027027,9.10058394160584,1.5386013986014,1.34816176470588,1.12830769230769,1.17344,...,26.5191349480969,35.1146655791191,35.0909090909091,46.322267920094,56.0614340588989,49.7500375469337,65.35100135318,0,0,0
2,Angola,-11.202692,17.873887,AO,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Albania,41.153332,20.168331,AL,41.3370909090909,36.0454501216545,35.6877678571429,29.0525603864734,7.88233644859813,8.27425641025641,...,9.36766375545852,10.6226587301587,13.6912008733624,11.4832985386221,13.4175670498084,4.48429980276134,0.297525354969574,0,0,0
5,Andorra,42.546245,1.601554,AD,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
joined_total.to_csv("../Resources/Cleaned_CSV/Total_Emission_Data.csv", index=False)
joined_gas.to_csv("../Resources/Cleaned_CSV/Gas_Emission_Data.csv", index=False)
joined_liquid.to_csv("../Resources/Cleaned_CSV/Liquid_Emission_Data.csv", index=False)
joined_solid.to_csv("../Resources/Cleaned_CSV/Solid_Emission_Data.csv", index=False)